application:
  province: USA

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/hr_management
    password: 12345678
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: Rrj1Zt3nN5WQ1mQ8QhaZc2m2YpQk8bq0f1H2e3r4t5u6v7w8x9y0zA==

server:
  port: 8080